name: CI/CD For React_app

on:
  push:
    branches:
      - master

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Install dependencies
          run: npm install

        - name: Build website
          run: npm run build

        - name: Slack Status
          if: always()
          uses: slackapi/slack-github-action@v1.23.0
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            SLACK_PR_CHANNEL_ID: ${{ secrets.SLACK_PR_CHANNEL_ID }}
          with:
            channel-id: ${{ secrets.SLACK_PR_CHANNEL_ID }}
            payload: |
              {
                "text": "GitHub Action build result: *${{ job.status }}*\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "GitHub Action build result: *${{ job.status }}* ${{ github.event_name }} ${{ github.workflow }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    }
                  }
                ]
              }
        

        # - name: Slack Status
        #   if: always()
        #   uses: ravsamhq/notify-slack-action@v1
        #   env:
        #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        #   with:
        #     status: ${{ job.status }}
        #     notify_when: 'failure,success'
        #     notification_title: 'CI/CD On {repo}'
        #     message_format: '{emoji} *{workflow}* is *{status_message}*'
        #     footer: 'Linked to Repo <{repo_url}|{repo}>'

