name: Testing for Slack notifiction for Actions 

on:
  push:
    branches:
      - master

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Install dependencies
          run: npm install

        - name: Build website
          run: npm run build

        - name: Slack Status
          if: always()
          uses: ravsamhq/notify-slack-action@v1
          with:
            status: ${{ job.status }}
            notify_when: 'failure,success'
            status: ${{ job.status }} # required
            notify_when: 'failure'
            notification_title: '{workflow} has {status_message}'
            message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
            footer: 'Linked to Repo <{repo_url}|{repo}>'
            notify_when: 'failure,success'
            # mention_users: 'U0160UUNH8S,U0080UUAA9N'
            mention_users_when: 'failure,warnings,success'
            # mention_groups: 'SAZ94GDB8'
            mention_groups_when: 'failure,warnings,success'
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

  # messageSlack:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #   - name: Slack Notification
  #     id: slack
  #     uses: slackapi/slack-github-action@v1.23.0
  #     with:
  #       payload: |
  #         {
  #           "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
  #           "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
  #           "blocks": [
  #             {
  #               "type": "section",
  #               "text": {
  #                 "type": "mrkdwn",
  #                 "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
  #               }
  #             }
  #           ]
  #         }
  #     env:
  #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #       SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  #     if: always()




    # - name: Notification Slack
    #   uses: slackapi/slack-github-action@v1.23.0
    #   env:
    #     SLACK_CHANNEL: actions_slack-alert
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    #     SLACK_MESSAGE: "This is Testing."

  