name: Testing for Slack notifiction for Actions 

on:
  push:
    branches:
      - master

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Install dependencies
          run: npm install

        - name: Build website
          run: npm run build

  messageSlack:
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    # - name: Notification Slack
    #   uses: slackapi/slack-github-action@v1.23.0
    #   env:
    #     SLACK_CHANNEL: actions_slack-alert
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    #     SLACK_MESSAGE: "This is Testing."

  